version: '3'
services:
  php:
    image: webdevops/php:7.4
    container_name: tax_php
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 5000M
      PHP_POST_MAX_SIZE: 5000M
    volumes:
      - "./:/laravel"
    working_dir: '/laravel'
  nginx:
    depends_on:
      - php
    image: webdevops/nginx
    container_name: tax_nginx
    environment:
      WEB_DOCUMENT_ROOT: /laravel
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000
    volumes:
      - "./:/laravel"
    ports:
      - "9000:80"
